services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking-api-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banfico
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  frontend:
    build:
      context: ./banking-frontend
      dockerfile: Dockerfile
    container_name: banking-api-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:16
    container_name: banking-api-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: banfico
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: