services:
  gateway:
    image: nginx:1.27-alpine
    container_name: banking-api-gateway
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
      - keycloak
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking-api-backend
    depends_on:
      - postgres
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banfico
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8080/auth/realms/our-bank
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/auth/realms/our-bank/protocol/openid-connect/certs
      KEYCLOAK_ADMIN_SERVER_URL: http://keycloak:8080/auth
      KEYCLOAK_ADMIN_REALM: our-bank
      KEYCLOAK_ADMIN_USERNAME: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN_CLIENT_ID: admin-cli

  frontend:
    build:
      context: ./banking-frontend
      dockerfile: Dockerfile
    container_name: banking-api-frontend
    depends_on:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: banking-api-keycloak
    command: start-dev --http-relative-path=/auth --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_PROXY_HEADERS: xforwarded
    volumes:
      - ./keycloak:/opt/keycloak/data/import:ro

  postgres:
    image: postgres:16
    container_name: banking-api-postgres
    environment:
      POSTGRES_DB: banfico
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: