spring.application.name=banking-api

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/banfico
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/our-bank

keycloak.admin.server-url=http://localhost:8080/auth
keycloak.admin.realm=our-bank
keycloak.admin.username=admin
keycloak.admin.password=admin
keycloak.admin.client-id=admin-cli